{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    microservice: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: {{ .Values.service.port | default 80 }}
    protocol: TCP
    targetPort: {{ .Values.service.port | default 80 }}
  selector:
    microservice: {{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
{{- end }}